spring:
  application:
    name: techefx-property-access-service
  profiles:
    active: dev

server:
  port: ${port:8100}

spring.config.import: "optional:configserver:"

management:
  endpoints:
    web:
      exposure:
        include: refresh

